### ISSUE TITLE
Two issues with TAQ

### ISSUE THREAD

**Issue by ivanfig** [Spreads/Spreads#39]
On this line:

var dbPersistor = new DatabasePersistor("taq", new MySqlMigrationsConfiguration(), 
                new MySqlDistributedMigrationsConfiguration(), updateMigrations: true);

I can't seem to find where the classes MySqlMigrationsConfiguration and MySqlDistributedMigrationsConfiguration are?

and also

I don't seem to be able to find the Nuget Package for Prism? Not sure if this is related to above problem

I am using VS15 Community Edition.

**Comment by buybackoff** [comment]
please disregard this stuff. that was based on private stuff, but as of 0.3.5 it should work, but with a lot of changes. storage is now a part of Spreads, but i cannot document anything at this point.

**Comment by buybackoff** [comment]
SeriesStorage class is what you need to get a persistent writable series. The rest of the example should just work with it.

**Comment by ivanfig** [comment]
Thanks for the prompt response. I replaced the code with

            var connectionString = "Data Source=perf_test.db;";
            var store = new SeriesStorage(connectionString);

and it seems to compile. However, I don't see anywhere in the projects where Main2 or Main3 is called?

**Comment by buybackoff** [comment]
Main2/3 was just some testing... This was not meant for public usage, just committed here for convenience. I will write a blog post soon on all these things.

**Comment by ivanfig** [comment]
Victor thanks with your help I have several unit tests going now.

**Comment by ivanfig** [comment]
New issue

My computer has 8GB of RAM running Windows 2008 Server R2 Standard x64. 

It bombs after a while with an exception {"Exception of type 'System.OutOfMemoryException' was thrown."}. According to the TAsk Manager, memory usage is only at ~4GB at the line series = store.GetPersistentOrderedMap<DateTime, TaqTrade>(symbol);

IPersistentOrderedMap<DateTime, TaqTrade> series;
                    if (!seriesDictionary.TryGetValue(symbol, out series)) {
                        series = store.GetPersistentOrderedMap<DateTime, TaqTrade>(symbol);
                        seriesDictionary[symbol] = series;
                    }



   at System.Text.Encoding.GetBytes(String s)
   at Microsoft.Data.Sqlite.Interop.MarshalEx.StringToHGlobalUTF8(String s, Int32& length)
   at Microsoft.Data.Sqlite.Interop.NativeMethods.sqlite3_prepare_v2(Sqlite3Handle db, String zSql, Sqlite3StmtHandle& ppStmt, String& pzTail)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at Dapper.SqlMapper.ExecuteReaderWithFlagsFallback(IDbCommand cmd, Boolean wasClosed, CommandBehavior behavior)
   at Dapper.SqlMapper.<QueryImpl>d__69`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at Spreads.Storage.SeriesStorage.GetLongId[K,V](String seriesId)
   at Spreads.Storage.SeriesStorage.GetPersistentOrderedMap[K,V](String seriesId)
   at TAQParse.Program.Main3(String[] args) in C:\Users\Administrator\Documents\Spreads.TAQParser\Spreads.TAQParser\Program.cs:line 111
   at TAQParse.Program.Main(String[] args) in C:\Users\Administrator\Documents\Spreads.TAQParser\Spreads.TAQParser\Program.cs:line 48
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by buybackoff** [comment]
Make sure it actually runs as x64, not x86, in build config

**Comment by ivanfig** [comment]
That fixed it. Thanks.

**Comment by ivanfig** [comment]
New issue, when executing Main2, on the line var msft = store.GetPersistentOrderedMap<DateTime, TaqTrade>("msft").Map(t => t.TradePrice / 10000.0);

It gives the following Assertion

---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----

---- Assert Long Message ----

   at <StartupCode$Spreads-Collections>.$SortedChunkedMap.GetCursor@305-6.Spreads-ICursor`2-MoveAt(K key, Lookup direction)
   at <StartupCode$Spreads-Collections>.$SortedChunkedMap.GetCursor@305-6.Spreads-ICursor`2-Clone()
   at Spreads.BatchMapValuesCursor`3..ctor(Func`1 cursorFactory, Func`2 f, FSharpOption`1 fBatch)
   at Spreads.BatchMapValuesCursor`3.Clone()
   at Spreads.BatchMapValuesCursor`3.Spreads-ICursor`2-Clone()
   at Spreads.RepeatCursor`2.Spreads-ICursor`2-TryGetValue(K key, V& value)
   at Spreads.ZipNCursor`3.fillContinuousValuesAtKey(K key)
   at Spreads.ZipNCursor`3.MoveFirst()
   at Spreads.ZipNCursor`3.MoveNext()
   at Spreads.SeriesExtensions.ToSortedMap[K,V](ISeries`2 source)
   at TAQParse.Program.Main2(String[] args) in C:\Users\Administrator\Documents\Spreads.TAQParser\Spreads.TAQParser\Program.cs:line 154
   at TAQParse.Program.Main(String[] args) in C:\Users\Administrator\Documents\Spreads.TAQParser\Spreads.TAQParser\Program.cs:line 49
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by buybackoff** [comment]
Well, there is some issue in SCM that when fixed causes another issue, and
I haven't had time to properly debug.
See this for the fix:
https://github.com/Spreads/Spreads/commit/31e074c2a2c77664df2207342a8e5a453bb5c3c0

and then revert here:
https://github.com/Spreads/Spreads/commit/98b04af45e0d47b285e919f5318384e7fbcef452

This is a part of https://github.com/Spreads/Spreads/issues/9

**Comment by ivanfig** [comment]
What do I do if I just use the NuGet packages? I am not able to build from source.

**Comment by buybackoff** [comment]
Well, that is the cost of using alpha :)

**Comment by buybackoff** [comment]
@ivanfig  Could you please use master head and try again?

**Comment by ivanfig** [comment]
For some reason the Spreads.Extensions is not pulling in all Nuget packages. I am trying to uninstall and reinstall by hand to see what happens...

**Comment by ivanfig** [comment]
Looks like you are targeting .Net 4.5 and many of these packages require 4.5.2 or later.

**Comment by ivanfig** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0122	'Sqlite3Handle' is inaccessible due to its protection level	Spreads.Extensions	C:\Users\Administrator\Documents\Spreads\src\Spreads.Extensions\Storage\SQLite\Interop\NativeMethodsEx.cs	22	Active


Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'DllName' does not exist in the current context	Spreads.Extensions	C:\Users\Administrator\Documents\Spreads\src\Spreads.Extensions\Storage\SQLite\Interop\NativeMethodsEx.cs	65	Active

etc...


using System;
using System.Diagnostics;
using System.Runtime.InteropServices;

namespace Microsoft.Data.Sqlite.Interop {

    internal static partial class NativeMethods {

        static NativeMethods()
        {
            // Bootstrapper's static ctor loads native dlls
            Trace.Assert(Bootstrap.Bootstrapper.Instance.BaseFolder.Length > 0);
        }

        public static int sqlite3_blob_bytes(Sqlite3BlobHandle pBlob)
            => Sqlite3.blob_bytes(pBlob);

        public static int sqlite3_blob_close(IntPtr pBlob)
            => Sqlite3.blob_close(pBlob);

        public static int sqlite3_blob_open(Sqlite3Handle ppDb, string db, string table, string column, long iRow,
            int flags, out Sqlite3BlobHandle ppBlob) {
            var zDb = MarshalEx.StringToHGlobalUTF8(db);
            var zTable = MarshalEx.StringToHGlobalUTF8(table);
            var zColumn = MarshalEx.StringToHGlobalUTF8(column);

**Comment by buybackoff** [comment]
There are some git submodules that are easy to get wrong. But I regularly
work with the repo from two machines daily and all works fine and all
packages do restore automatically.

**Comment by ivanfig** [comment]
I downloaded the head. Then I hit rebuild. It goes and downloads nuget packages, and then gives a bunch of errors.

**Comment by buybackoff** [comment]
Try to explicitly sync submodulues in the lib folder... There is nothing
special in the project other than that. Or just try to fix you errors and
let me know what they were.

**Comment by buybackoff** [comment]
4.5.2 is 4.5, they the former should normally work with the later unless
there is special target in nuget.

**Comment by ivanfig** [comment]
How do I "explicitly sync submodulues in the lib folder" ?

**Comment by ivanfig** [comment]
Ok I tried this and it seems to work:

Update-Package -Reinstall -ProjectName Spreads.Extensions

**Comment by ivanfig** [comment]
I have no idea how this gets so confused. I don't see Dapper anywhere in the project, but the NuGet GUI says it is installed.

**Comment by ivanfig** [comment]
I give up for now since I am at an impasse. Even after refreshing the references by hand, it gives a ton of errors.

Maybe give in the readme exact instructions to the newget console on how to refresh the packages.

**Comment by buybackoff** [comment]
Thanks a lot for trying it anyway. I have been cleaning the stuff out and
shortly it should work with examples. No time for this now, sorry. Just
making it work properly. The next nuget should work...

**Comment by ivanfig** [comment]
Ok looking forward to it! Thanks.

**Comment by buybackoff** [comment]
Everything just works with the new storage and HEAD. Need to place FSharp.Charting where fsx expects it.
